# Generated by Django 5.0.1 on 2024-01-21 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='max_num_catagory',
            new_name='max_num_category',
        ),
    ]
