# Generated by Django 5.0.1 on 2024-01-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='link',
            name='priority',
            field=models.CharField(choices=[('default', 'Default'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent'), ('critical', 'Critical'), ('normal', 'Normal')], default='default', max_length=50),
        ),
        migrations.AlterField(
            model_name='link',
            name='status',
            field=models.CharField(choices=[('default', 'Default'), ('need', 'Need'), ('finished', 'Finished'), ('go_back_to', 'Go Back To'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('canceled', 'Canceled'), ('pending_approval', 'Pending Approval'), ('draft', 'Draft'), ('scheduled', 'Scheduled'), ('archived', 'Archived')], default='default', max_length=50),
        ),
    ]
